### ISSUE TITLE
[v1.116] BrokenPipeError: [Errno 32] Broken pipe

### ISSUE THREAD

**Issue by Goon3r** [illusion0001/libhijacker#13]
Hello,

**Operating System:** MacOS Monteray 12.6
**Python:** 3.116
**aiofiles:** 23.2.1
**libhijacker:** 1.116

When running the `send_elf.py` script the following is output in the terminal before exiting:
```sh
python3 send_elf.py <ps5_ip>
/Goon3r/PS5/libhijacker_1.116-01407445/send_elf.py: start
has_daemon: False
start send_spawner(args)
Traceback (most recent call last):
  File "~/Goon3r/PS5/libhijacker_1.116-01407445/send_elf.py", line 375, in <module>
    main()
  File "~/Goon3r/PS5/libhijacker_1.116-01407445/send_elf.py", line 369, in main
    asyncio.run(run_loggers(args))
  File "/usr/local/Cellar/python@3.11/3.11.6/Frameworks/Python.framework/Versions/3.11/lib/python3.11/asyncio/runners.py", line 190, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "/usr/local/Cellar/python@3.11/3.11.6/Frameworks/Python.framework/Versions/3.11/lib/python3.11/asyncio/runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/Cellar/python@3.11/3.11.6/Frameworks/Python.framework/Versions/3.11/lib/python3.11/asyncio/base_events.py", line 653, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "~/Goon3r/PS5/libhijacker_1.116-01407445/send_elf.py", line 295, in run_loggers
    await send_spawner(args)
  File "~/Goon3r/PS5/libhijacker_1.116-01407445/send_elf.py", line 268, in send_spawner
    await logger_client(args)
  File "~/Goon3r/PS5/libhijacker_1.116-01407445/send_elf.py", line 254, in logger_client
    await writer.drain()
  File "/usr/local/Cellar/python@3.11/3.11.6/Frameworks/Python.framework/Versions/3.11/lib/python3.11/asyncio/streams.py", line 377, in drain
    await self._protocol._drain_helper()
  File "/usr/local/Cellar/python@3.11/3.11.6/Frameworks/Python.framework/Versions/3.11/lib/python3.11/asyncio/streams.py", line 172, in _drain_helper
    await waiter
  File "/usr/local/Cellar/python@3.11/3.11.6/Frameworks/Python.framework/Versions/3.11/lib/python3.11/asyncio/selector_events.py", line 1082, in _write_ready
    n = self._sock.send(self._buffer)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
BrokenPipeError: [Errno 32] Broken pipe
```
Despite the script exiting, I do see debug notifications display on the PS5. I forgot to note the first ones seen but one subsequent calls it shows "libhijacker spawner main entered"

Can you adivse please?

Thanks,
Goon3r

**Comment by illusion0001** [comment]
Try commenting out line 254

**Comment by nirav-resideo** [comment]
> Try commenting out line 254

This doen't solve the problem.
